import { loader } from "./components/loader.js";
import { chatbot } from "./components/chatbot.js";
import { footer } from "./components/footer.js";
import { download } from "./components/download.js";
import { posts } from "./components/posts.js";
import { action } from "./components/action.js";
import { connect } from "./components/connect.js";
import { features } from "./components/features.js";
import { counter } from "./components/counter.js";
import { dashboard } from "./components/dashboard.js";
import { nav } from "./components/nav.js";

// loader("loader");
nav("navbar", "big-nav", "small-nav");
dashboard("dashboard");
counter("counter");
features("features");
connect("connect");
action();
posts();
download();
footer();
chatbot();
